name: count_me
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobx: ^2.4.0
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  mobx_codegen: ^2.6.2
  build_runner: ^2.4.13
  dio: ^5.7.0
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/